name: zhuhoutianying
on:
  workflow_dispatch:

  schedule:
    - cron: '38 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhuhoutianying
        env:
          g4: ${{ secrets.g4 }}
        run: |
          printf '%s' "$g4" | jq -r .mqiai1884 | /bin/bash
          printf '%s' "$vnv79" | jq -r .ivddl48 | /bin/bash
          printf '%s' "$pu15" | jq -r .ki18666 | /bin/bash
          printf '%s' "$pzgl39" | jq -r .jcuo2642 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EQPb8E8J
          path: "*.zip"
          retention-days: 1
